version: "3"

networks:
  lottery-bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24

#端口号 20101-
services:
  #portainer
  portainer:
    image: portainer/portainer:1.24.1
    container_name: portainer
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer/data:/data"
      - "./portainer/Portainer-CN:/public"   # 汉化
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports: # 映射端口
      - "20101:9000"
    networks:
      - lottery-bridge

  # zookeeper服务
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: unless-stopped
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/datalog:/datalog"
    ports:
      - "20102:2181"
    networks:
      - lottery-bridge

  # 可视化界面
  zookeeper-webui:
    image: tobilg/zookeeper-webui
    container_name: zookeeper-webui
    restart: unless-stopped
    environment:
      ZK_DEFAULT_NODE: zookeeper:2181
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "20103:8080"
    networks:
      - lottery-bridge

  #mysql
  mysql:
    image: mysql:8.0
    container_name: mysql8.0
    restart: unless-stopped
    volumes:
      - "./mysql8.0/my.cnf:/etc/mysql/my.cnf"
      - "./mysql8.0/data:/var/lib/mysql"
      - "./mysql8.0/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./mysql8.0/mysql-files:/var/lib/mysql-files"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: mysql@123
    ports:
      - "20104:3306"
    networks:
      lottery-bridge:
        ipv4_address: 172.22.0.4

  #redis
  redis:
    image: redis:6.0.8
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly no # 启动redis服务并添加密码为：123456,默认不开启redis-aof方式持久化配置
    #    command: redis-server --requirepass 123456 --appendonly yes # 启动redis服务并添加密码为：123456,并开启redis持久化配置
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis/data:/data"
      - "./redis/config/redis.conf:/etc/redis/redis.conf"
    ports: # 映射端口
      - "20105:6379"
    networks:
      - lottery-bridge

  #nacos
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: unless-stopped
    volumes:
      - ./nacos/logs:/home/nacos/logs
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MODE: standalone
    ports:
      - "20106:8848"
    networks:
      - lottery-bridge

  #xxl-job
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    restart: unless-stopped
    environment:
      # TODO 根据自己的配置修改，配置项参考源码文件：/xxl-job/xxl-job-admin/src/main/resources/application.properties
      PARAMS: "--spring.datasource.url=jdbc:mysql://172.22.0.4:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=mysql@123
               --server.servlet.context-path=/xxl-job-admin
               --xxl.job.accessToken=2023xxl_job"
    depends_on:
      - mysql
    ports:
      - "20107:8080"
    networks:
      - lottery-bridge

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    restart: unless-stopped
    privileged: true
    environment:
      - PMA_HOST= mysql
      - PMA_PORT= 3306
    depends_on:
      - mysql
    ports:
      - "20108:80"
    networks:
      - lottery-bridge

  #nging 网站管理
  nging:
    container_name: nging
    image: admpub/nging:latest
    depends_on:
      - mysql
    expose:
      - 9999
    ports:
      - 20109:9999
    links:
      - "mysql:mysql"
    volumes:
      - ./nging-data/nging/data/cache:/home/nging_linux_amd64/data/cache
      - ./nging-data/nging/data/ftpdir:/home/nging_linux_amd64/data/ftpdir
      - ./nging-data/nging/data/logs:/home/nging_linux_amd64/data/logs
      - ./nging-data/nging/data/sm2:/home/nging_linux_amd64/data/sm2
      - ./nging-data/nging/myconfig:/home/nging_linux_amd64/myconfig
      - ./nging-data/nging/public:/home/nging_linux_amd64/public
    command: [ "-p", "9999", "-c", "myconfig/config.yaml" ]
    restart: always
    networks:
      - lottery-bridge